# Generated by Django 3.2.25 on 2024-07-04 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusanDistrict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_name', models.CharField(max_length=100)),
                ('population', models.IntegerField()),
                ('area', models.FloatField()),
                ('major_facility', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.RemoveField(
            model_name='board',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='board',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='board',
            name='writer',
        ),
        migrations.AlterField(
            model_name='board',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
